name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-node-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Run Unit Tests
    #   run: |
    #     # Explicitly tests code in src/ and scripts/, avoids trying to run .ipynb files
    #     pytest tests/
        pip install pytest pytest-html
      - name:  Run Unit Tests
        run: |
          pytest src/tests/test_preprocess.py
        continue-on-error: true  # Continue even if tests fail to ensure report is generated
      - name: Upload Test Report
        if: always()  # Ensure this step runs even if previous steps 
        uses: actions/upload-artifact@v5
        with:
          name: test-report
          path: report.html